services:
  http-app-bridge:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "15000:5000"
  http-app-host:
    network_mode: "host"
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PORT=16000