version: "3"
services:
  http-app:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - 6890
    deploy:
      replicas: 2 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载自定义的 Nginx 配置
    ports:
      - "6892:6892"          # 将 Nginx 的 6890 端口映射到主机
      - "6800:80"
    depends_on:
      - http-app

 